### ISSUE TITLE
add minimal documentation

### ISSUE THREAD

**Issue by kdaily** [bsmn/bsmn-pipeline#1]
There is currently no documentation on how to set up the infrastructure required, how to set up the list of data to process (data source? table? query?), and very little on how to run.

**Comment by bintriz** [comment]
Do you mean how to configure cfncluster itself? I'm not sure how manual configuration of cfncluster be included inside this codebase. We might need to make the current approach of configuring cfncluster simpler first.

**Comment by kdaily** [comment]
Partially addressed by #9 and #10.

**Comment by kdaily** [comment]
Looks pretty good!
