### ISSUE TITLE
test first step of containerized, cwl pipeline

### ISSUE THREAD

**Issue by kdaily** [bsmn/bsmn-pipeline#20]
I implemented the first step of the mapping pipeline using `bwa mem`. It is viewable here:

https://dockstore.org/my-tools/registry.hub.docker.com/dailyk/dockstore-tool-bwa-mem/bwa-mem

This contains a `Dockerfile` and CWL tool description.

I need to provide a CWL workflow to run this step.

**Comment by attilagk** [comment]
@kdaily sorry I have just looked at your implementation of mapping.  Is it something that could become part of the `bsmn-pipeline`?  I am not familiar with docker; some software needs to be installed before the tool can be used, right?

**Comment by kdaily** [comment]
Hi @attilagk sorry for not responding here. That's the intention!

I have implemented this entire step now: https://github.com/bsmn/bsmn-pipeline/blob/master/genome_mapping/job_scripts/aln_1.align_sort.sh

The CWL + docker implementation is here: https://github.com/bsmn/bsmn-common-workflow

I'm going to track work over there and close CWL testing related things here. I'll still open tickets re: clarification of the existing pipeline as I continue to implement it there.
