### ISSUE TITLE
PON Mask for hg38

### ISSUE THREAD

**Issue by wdecoster** [bsmn/bsmn-pipeline#29]
Hi,

I noticed that, in contrast to all other resources, there is just one PON mask. Is this compatible with hg38 or just with hg19?

Thanks,
Wouter

**Comment by yjjang** [comment]
It should work for both hg19 and hg38. Actually PON mask itself is based on hg38. We use the UCSC [LiftOver](https://genome-store.ucsc.edu) for processing hg19 input.

**Comment by wdecoster** [comment]
Great, thanks!
